In [2]:
import pandas as pd
df = pd.read_csv('berkshire_holdings_combined.csv')
df

,cusip,nameOfIssuer,titleOfClass,periodOfReport,value,shrs_or_prn_amt
0,00287Y109,ABBVIE INC,COM,2020-09-30,1862541,21264316
1,00287Y109,ABBVIE INC,COM,2020-12-31,2735870,25533082
2,00287Y109,ABBVIE INC,COM,2021-03-31,2474794,22868178
3,00287Y109,ABBVIE INC,COM,2021-06-30,2312258,20527861
4,00287Y109,ABBVIE INC,COM,2021-09-30,1553165,14398488
...,...,...,...,...,...,...
779,G9001E128,LIBERTY LATIN AMERICA LTD,COM CL C,2023-12-31,9424707,1284020
780,G9001E128,LIBERTY LATIN AMERICA LTD,COM CL C,2024-03-31,8975300,1284020
781,H1467J104,CHUBB LIMITED,COM,2023-09-30,1695320075,8143530
782,H1467J104,CHUBB LIMITED,COM,2023-12-31,4542600000,20100000
783,H1467J104,CHUBB LIMITED,COM,2024-03-31,6717644659,25923840